# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.runs/synth_2/caribou_top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_2" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.cache/wt [current_project]
set_property parent.project_path /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /home/pct/Caribou/MPW4_Helmut/MPW3/ip_repo/control_register_1.0
  /home/pct/Caribou/MPW4_Helmut/MPW3/ip-repo
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/cw_8b10b_enc.sv
read_vhdl -library xil_defaultlib {
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/DDR_IN_SHIFT.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/GBE_SFP.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/SIN.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/TLU_TDH.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/check_for_ARP_request.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/check_for_ping_request.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/data_reg_buffer.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/dec_8b10b.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/decode_fifo.vhd
  /home/pct/Caribou/MPW4_Helmut/ip_repo/heartbeat.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/reset_TS.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/send_SOUT_testpattern_sm.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/ser_out.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/sim_TLU_aida_fsm.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/sim_TLU_fsm.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/transmit_arp_reply.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/transmit_fsm.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/sources/transmit_ping_reply.vhd
  /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/caribou_top_wrapper.vhd
}
add_files /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/caribou_top.bd
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_processing_system7_0_0/caribou_top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_rst_ps7_0_100M_0/caribou_top_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_rst_ps7_0_100M_0/caribou_top_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_rst_ps7_0_100M_0/caribou_top_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_0/caribou_top_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_0/caribou_top_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_fifo_mm_s_0_1/caribou_top_axi_fifo_mm_s_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_fifo_mm_s_1_0/caribou_top_axi_fifo_mm_s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_0/caribou_top_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_0/caribou_top_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_0/caribou_top_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_1/caribou_top_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_1/caribou_top_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_0_1/caribou_top_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_2_0/caribou_top_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_2_0/caribou_top_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_2_0/caribou_top_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_3_0/caribou_top_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_3_0/caribou_top_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_3_0/caribou_top_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_xbar_0/caribou_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_4_0/caribou_top_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_4_0/caribou_top_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_4_0/caribou_top_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_5_0/caribou_top_axi_gpio_5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_5_0/caribou_top_axi_gpio_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_5_0/caribou_top_axi_gpio_5_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_6_0/caribou_top_axi_gpio_6_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_6_0/caribou_top_axi_gpio_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_6_0/caribou_top_axi_gpio_6_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_7_0/caribou_top_axi_gpio_7_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_7_0/caribou_top_axi_gpio_7_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_7_0/caribou_top_axi_gpio_7_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_8_0/caribou_top_axi_gpio_8_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_8_0/caribou_top_axi_gpio_8_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_gpio_8_0/caribou_top_axi_gpio_8_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_14/caribou_top_auto_pc_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_0_1/caribou_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_1/caribou_top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_2/caribou_top_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_3/caribou_top_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_4/caribou_top_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_5/caribou_top_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_6/caribou_top_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_7/caribou_top_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_8/caribou_top_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_9/caribou_top_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_10/caribou_top_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_11/caribou_top_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_12/caribou_top_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_auto_pc_13/caribou_top_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/caribou_top_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/synth/gig_ethernet_pcs_pma_1.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/synth/gig_ethernet_pcs_pma_1_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_clocks.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/data_fifo/data_fifo.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/data_fifo/data_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/data_fifo/data_fifo_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_div/clk_div.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_div/clk_div_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_div/clk_div.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_div/clk_div_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo.xci
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/pin_assignment.xdc
set_property used_in_implementation false [get_files /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/pin_assignment.xdc]

read_xdc /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/timing_constraints.xdc
set_property used_in_implementation false [get_files /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/timing_constraints.xdc]

read_xdc /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/new/location_constraints.xdc
set_property used_in_implementation false [get_files /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/new/location_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top caribou_top_wrapper -part xc7z045ffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef caribou_top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_2_synth_report_utilization_0" "report_utilization -file caribou_top_wrapper_utilization_synth.rpt -pb caribou_top_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_2" END { }
