# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources/pin_assignment.xdc

# XDC: imports/sources/timing_constraints.xdc

# XDC: new/location_constraints.xdc

# Block Designs: bd/caribou_top/caribou_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top || ORIG_REF_NAME==caribou_top} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_processing_system7_0_0/caribou_top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_processing_system7_0_0 || ORIG_REF_NAME==caribou_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_rst_ps7_0_100M_0/caribou_top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==caribou_top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_ps7_0_axi_periph_1/caribou_top_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_ps7_0_axi_periph_1 || ORIG_REF_NAME==caribou_top_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_xlconcat_1_0/caribou_top_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_xlconcat_1_0 || ORIG_REF_NAME==caribou_top_xlconcat_1_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_iic_0_0/caribou_top_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_iic_0_0 || ORIG_REF_NAME==caribou_top_axi_iic_0_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_fifo_mm_s_0_1/caribou_top_axi_fifo_mm_s_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_fifo_mm_s_0_1 || ORIG_REF_NAME==caribou_top_axi_fifo_mm_s_0_1} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_fifo_mm_s_1_0/caribou_top_axi_fifo_mm_s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==caribou_top_axi_fifo_mm_s_1_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_0_0/caribou_top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_0_0 || ORIG_REF_NAME==caribou_top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_0_1/caribou_top_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_0_1 || ORIG_REF_NAME==caribou_top_axi_gpio_0_1} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_2_0/caribou_top_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_2_0 || ORIG_REF_NAME==caribou_top_axi_gpio_2_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_3_0/caribou_top_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_3_0 || ORIG_REF_NAME==caribou_top_axi_gpio_3_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_iic_0_1 || ORIG_REF_NAME==caribou_top_axi_iic_0_1} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_register_array_v_0_0/caribou_top_axi_register_array_v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_register_array_v_0_0 || ORIG_REF_NAME==caribou_top_axi_register_array_v_0_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_xbar_0/caribou_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_xbar_0 || ORIG_REF_NAME==caribou_top_xbar_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_4_0/caribou_top_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_4_0 || ORIG_REF_NAME==caribou_top_axi_gpio_4_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_5_0/caribou_top_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_5_0 || ORIG_REF_NAME==caribou_top_axi_gpio_5_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_6_0/caribou_top_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_6_0 || ORIG_REF_NAME==caribou_top_axi_gpio_6_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_7_0/caribou_top_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_7_0 || ORIG_REF_NAME==caribou_top_axi_gpio_7_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_axi_gpio_8_0/caribou_top_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_axi_gpio_8_0 || ORIG_REF_NAME==caribou_top_axi_gpio_8_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_14/caribou_top_auto_pc_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_14 || ORIG_REF_NAME==caribou_top_auto_pc_14} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_0_1/caribou_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_0 || ORIG_REF_NAME==caribou_top_auto_pc_0} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_1/caribou_top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_1 || ORIG_REF_NAME==caribou_top_auto_pc_1} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_2/caribou_top_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_2 || ORIG_REF_NAME==caribou_top_auto_pc_2} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_3/caribou_top_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_3 || ORIG_REF_NAME==caribou_top_auto_pc_3} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_4/caribou_top_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_4 || ORIG_REF_NAME==caribou_top_auto_pc_4} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_5/caribou_top_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_5 || ORIG_REF_NAME==caribou_top_auto_pc_5} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_6/caribou_top_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_6 || ORIG_REF_NAME==caribou_top_auto_pc_6} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_7/caribou_top_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_7 || ORIG_REF_NAME==caribou_top_auto_pc_7} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_8/caribou_top_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_8 || ORIG_REF_NAME==caribou_top_auto_pc_8} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_9/caribou_top_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_9 || ORIG_REF_NAME==caribou_top_auto_pc_9} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_10/caribou_top_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_10 || ORIG_REF_NAME==caribou_top_auto_pc_10} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_11/caribou_top_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_11 || ORIG_REF_NAME==caribou_top_auto_pc_11} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_12/caribou_top_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_12 || ORIG_REF_NAME==caribou_top_auto_pc_12} -quiet] -quiet

# IP: bd/caribou_top/ip/caribou_top_auto_pc_13/caribou_top_auto_pc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==caribou_top_auto_pc_13 || ORIG_REF_NAME==caribou_top_auto_pc_13} -quiet] -quiet

# XDC: bd/caribou_top/caribou_top_ooc.xdc
