# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pins.xdc

# Block Designs: bd/LED_CH/LED_CH.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH || ORIG_REF_NAME==LED_CH} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_zynq_ultra_ps_e_0_0/LED_CH_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==LED_CH_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_axi_interconnect_0_0/LED_CH_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_axi_interconnect_0_0 || ORIG_REF_NAME==LED_CH_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_rst_ps8_0_99M_0/LED_CH_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_rst_ps8_0_99M_0 || ORIG_REF_NAME==LED_CH_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_axi_gpio_0_0/LED_CH_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_axi_gpio_0_0 || ORIG_REF_NAME==LED_CH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_led_blink_patterns_0_0/LED_CH_led_blink_patterns_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_led_blink_patterns_0_0 || ORIG_REF_NAME==LED_CH_led_blink_patterns_0_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_auto_ds_0/LED_CH_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_auto_ds_0 || ORIG_REF_NAME==LED_CH_auto_ds_0} -quiet] -quiet

# IP: bd/LED_CH/ip/LED_CH_auto_pc_0/LED_CH_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_CH_auto_pc_0 || ORIG_REF_NAME==LED_CH_auto_pc_0} -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/LED_CH_ooc.xdc
