# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/pct/Caribou/MPW4/LED_CH/LED_CH.runs/synth_1/LED_CH_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_msg_config  -id {Common 17-55}  -string {{ERROR: [Common 17-55] 'set_property' expects at least one object. [/home/yotarid/work/caribou/boreal/fw/src/usr/H2M/xdc/H2M_device_phy.tcl:11]
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.}}  -suppress 
set_msg_config  -id {Vivado 12-584}  -string {{WARNING: [Vivado 12-584] No ports matched 'fmc_dp_m2c_*_o[*]'. [/home/yotarid/work/caribou/boreal/fw/src/usr/H2M/xdc/H2M_device_phy.tcl:11]}}  -suppress 
set_msg_config  -id {Vivado 12-1411}  -string {{ERROR: [Vivado 12-1411] Cannot set LOC property of ports, Could not find a valid bel for the shape with the following elements: 
H2M_device_top_zcu102_i/H2M_device_0/inst/ibuf_gate_in/INBUF_INST
USER_SMA_CLOCK_P
H2M_device_top_zcu102_i/H2M_device_0/inst/ibuf_gate_in/IBUFCTRL_INST
 [/home/yotarid/work/caribou/boreal/usr/H2M/xdc/zcu102/H2M_device_phy_zcu102.tcl:48]}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pct/Caribou/MPW4/LED_CH/LED_CH.cache/wt [current_project]
set_property parent.project_path /home/pct/Caribou/MPW4/LED_CH/LED_CH.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_repo_paths /home/pct/Caribou/MPW4/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/pct/Caribou/MPW4/LED_CH/LED_CH.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/hdl/LED_CH_wrapper.v
add_files /home/pct/Caribou/MPW4/LED_CH/LED_CH.srcs/sources_1/bd/LED_CH/LED_CH.bd
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_zynq_ultra_ps_e_0_0/LED_CH_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_zynq_ultra_ps_e_0_0/LED_CH_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_rst_ps8_0_99M_0/LED_CH_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_rst_ps8_0_99M_0/LED_CH_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_rst_ps8_0_99M_0/LED_CH_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_axi_gpio_0_0/LED_CH_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_axi_gpio_0_0/LED_CH_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_axi_gpio_0_0/LED_CH_axi_gpio_0_0.xdc]
set_property used_in_synthesis false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_auto_ds_0/LED_CH_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_auto_ds_0/LED_CH_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_auto_ds_0/LED_CH_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/ip/LED_CH_auto_pc_0/LED_CH_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pct/Caribou/MPW4/LED_CH/LED_CH.gen/sources_1/bd/LED_CH/LED_CH_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pct/Caribou/MPW4/LED_CH/LED_CH.srcs/constrs_1/new/Pins.xdc
set_property used_in_implementation false [get_files /home/pct/Caribou/MPW4/LED_CH/LED_CH.srcs/constrs_1/new/Pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/pct/Caribou/MPW4/LED_CH/LED_CH.srcs/utils_1/imports/synth_1/LED_CH_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top LED_CH_wrapper -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LED_CH_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LED_CH_wrapper_utilization_synth.rpt -pb LED_CH_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
