# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/LED_2_patterns/LED_2_patterns.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns || ORIG_REF_NAME==LED_2_patterns} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_zynq_ultra_ps_e_0_1/LED_2_patterns_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==LED_2_patterns_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_proc_sys_reset_0_0/LED_2_patterns_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_proc_sys_reset_0_0 || ORIG_REF_NAME==LED_2_patterns_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_axi_interconnect_0_0/LED_2_patterns_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_axi_interconnect_0_0 || ORIG_REF_NAME==LED_2_patterns_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_led_blink_patterns_0_0/LED_2_patterns_led_blink_patterns_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_led_blink_patterns_0_0 || ORIG_REF_NAME==LED_2_patterns_led_blink_patterns_0_0} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_axi_gpio_0_0/LED_2_patterns_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_axi_gpio_0_0 || ORIG_REF_NAME==LED_2_patterns_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_auto_ds_0/LED_2_patterns_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_auto_ds_0 || ORIG_REF_NAME==LED_2_patterns_auto_ds_0} -quiet] -quiet

# IP: bd/LED_2_patterns/ip/LED_2_patterns_auto_pc_0/LED_2_patterns_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_2_patterns_auto_pc_0 || ORIG_REF_NAME==LED_2_patterns_auto_pc_0} -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4/LED_2_patterns_test/LED_2_patterns_test.gen/sources_1/bd/LED_2_patterns/LED_2_patterns_ooc.xdc
