#*****************************************************************************************
# Vivado (TM) v2018.3.1 (64-bit)
#
# MPW4.tcl: Tcl script for re-creating project 'caribou-soc'
#
# Generated by Vivado on Tue Jan 16 14:10:00 +0100 2024
# IP Build 2486929 on Tue Mar 26 06:44:21 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (MPW4.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/caribou_top.bd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/cw_8b10b_enc.sv"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/DDR_IN_SHIFT.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/SIN.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/TLU_TDH.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/data_reg_buffer.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/decode_fifo.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/send_SOUT_testpattern_sm.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/ser_out.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/sim_TLU_fsm.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/caribou_top_wrapper.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/CW_8b10b_dec.sv"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/shutter_TOT_counter.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/ADC9249.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/ADC9249_deser.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/ADC_rx_in_reg.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/FCO_reg.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/new/WBC_RBC_counters.vhd"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/ADC_clk_domain_fifo/ADC_clk_domain_fifo.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clk_div/clk_div.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/WBC_RBC_FIFO/WBC_RBC_FIFO.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/data_fifo/data_fifo.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_ADC_TLU_hist/fifo_ADC_TLU_hist.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_20MHz_to_320MHz/PLL_20MHz_to_320MHz.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_320MHz/PLL_40MHz_to_320MHz.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo.xci"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/pin_assignment.xdc"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/imports/sources/timing_constraints.xdc"
#    "C:/Users/steining/Desktop/MPW4/caribou-soc/caribou-soc.srcs/constrs_1/new/location_constraints.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/steining/Desktop/ip_repo/axi_register_array_1.0/hdl/axi_register_array_v1_0_S00_AXI.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/GBE_SFP.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/check_for_ARP_request.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/check_for_ping_request.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/dec_8b10b.vhd"
#    "C:/Users/steining/Desktop/ip_repo/heartbeat.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/reset_TS.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/sim_TLU_aida_fsm.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/transmit_arp_reply.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/transmit_fsm.vhd"
#    "C:/Users/steining/Desktop/MPW4/sources/transmit_ping_reply.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "caribou-soc"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "MPW4.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z045ffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:zc706:part0:1.3" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "zc706" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "target_simulator" -value "Questa" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "85" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "85" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "85" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "85" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "85" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "85" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "85" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../../MPW3/ip_repo/control_register_1.0"] [file normalize "$origin_dir/../../MPW3/ip-repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../ip_repo/axi_register_array_1.0/hdl/axi_register_array_v1_0_S00_AXI.vhd"] \
 [file normalize "${origin_dir}/../sources/GBE_SFP.vhd"] \
 [file normalize "${origin_dir}/../sources/check_for_ARP_request.vhd"] \
 [file normalize "${origin_dir}/../sources/check_for_ping_request.vhd"] \
 [file normalize "${origin_dir}/../sources/dec_8b10b.vhd"] \
 [file normalize "${origin_dir}/../../ip_repo/heartbeat.vhd"] \
 [file normalize "${origin_dir}/../sources/reset_TS.vhd"] \
 [file normalize "${origin_dir}/../sources/sim_TLU_aida_fsm.vhd"] \
 [file normalize "${origin_dir}/../sources/transmit_arp_reply.vhd"] \
 [file normalize "${origin_dir}/../sources/transmit_fsm.vhd"] \
 [file normalize "${origin_dir}/../sources/transmit_ping_reply.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/caribou_top.bd"]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/cw_8b10b_enc.sv" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/DDR_IN_SHIFT.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/SIN.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/TLU_TDH.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/data_reg_buffer.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/decode_fifo.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/send_SOUT_testpattern_sm.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/ser_out.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/sim_TLU_fsm.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/caribou_top_wrapper.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/CW_8b10b_dec.sv" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/shutter_TOT_counter.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/ADC9249.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/ADC9249_deser.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/ADC_rx_in_reg.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/bd/caribou_top/hdl/FCO_reg.vhd" ]\
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/new/WBC_RBC_counters.vhd" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../ip_repo/axi_register_array_1.0/hdl/axi_register_array_v1_0_S00_AXI.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/GBE_SFP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/check_for_ARP_request.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/check_for_ping_request.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/dec_8b10b.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../ip_repo/heartbeat.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/reset_TS.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/sim_TLU_aida_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/transmit_arp_reply.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/transmit_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sources/transmit_ping_reply.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
set file "caribou_top/caribou_top.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "hdl/cw_8b10b_enc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/DDR_IN_SHIFT.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/SIN.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/TLU_TDH.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/data_reg_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/decode_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/send_SOUT_testpattern_sm.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/ser_out.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/sim_TLU_fsm.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/caribou_top_wrapper.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/CW_8b10b_dec.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/shutter_TOT_counter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/ADC9249.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/ADC9249_deser.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/ADC_rx_in_reg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/FCO_reg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "new/WBC_RBC_counters.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "caribou_top_wrapper" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_0/clk_wiz_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/ADC_clk_domain_fifo/ADC_clk_domain_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ADC_clk_domain_fifo/ADC_clk_domain_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/clk_div/clk_div.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_div/clk_div.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/WBC_RBC_FIFO/WBC_RBC_FIFO.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "WBC_RBC_FIFO/WBC_RBC_FIFO.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/data_fifo/data_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "data_fifo/data_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/fifo_ADC_TLU_hist/fifo_ADC_TLU_hist.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_ADC_TLU_hist/fifo_ADC_TLU_hist.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_generator_0/fifo_generator_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_generator_1/fifo_generator_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/GBE_rx_fifo/GBE_rx_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "GBE_rx_fifo/GBE_rx_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/PLL_20MHz_to_320MHz/PLL_20MHz_to_320MHz.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "PLL_20MHz_to_320MHz/PLL_20MHz_to_320MHz.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_320MHz/PLL_40MHz_to_320MHz.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "PLL_40MHz_to_320MHz/PLL_40MHz_to_320MHz.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/transmit_fifo_1/transmit_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "transmit_fifo_1/transmit_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/caribou-soc.srcs/sources_1/ip/clock_domain_fifo/clock_domain_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clock_domain_fifo/clock_domain_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/caribou-soc.srcs/constrs_1/imports/sources/pin_assignment.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "sources/pin_assignment.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/caribou-soc.srcs/constrs_1/imports/sources/timing_constraints.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "sources/timing_constraints.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/caribou-soc.srcs/constrs_1/new/location_constraints.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/location_constraints.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/sources/pin_assignment.xdc" -objects $obj
set_property -name "target_ucf" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/imports/sources/pin_assignment.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "caribou_top_wrapper" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "synth_1_synth_report_utilization_0" -objects $obj

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'caribou_top_xlconcat_1_0_synth_1' run (if not found)
if {[string equal [get_runs -quiet caribou_top_xlconcat_1_0_synth_1] ""]} {
    create_run -name caribou_top_xlconcat_1_0_synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset caribou_top_xlconcat_1_0
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs caribou_top_xlconcat_1_0_synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs caribou_top_xlconcat_1_0_synth_1]
}
set obj [get_runs caribou_top_xlconcat_1_0_synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'caribou_top_xlconcat_1_0_synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_synth_1] caribou_top_xlconcat_1_0_synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs caribou_top_xlconcat_1_0_synth_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_synth_1] caribou_top_xlconcat_1_0_synth_1_synth_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_synth_1_synth_report_utilization_0" -objects $obj

}
set obj [get_runs caribou_top_xlconcat_1_0_synth_1]
set_property -name "constrset" -value "caribou_top_xlconcat_1_0" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'synth_2' run (if not found)
if {[string equal [get_runs -quiet synth_2] ""]} {
    create_run -name synth_2 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_2]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_2]
}
set obj [get_runs synth_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_2_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_2_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_2
}
set obj [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "synth_2_synth_report_utilization_0" -objects $obj

}
set obj [get_runs synth_2]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_2]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_init_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_opt_report_drc_0" -objects $obj

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_io_0" -objects $obj

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_utilization_0" -objects $obj

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_control_sets_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_1" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_post_place_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_drc_0" -objects $obj

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_methodology_0" -objects $obj

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_power_0" -objects $obj

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_route_status_0" -objects $obj

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_clock_utilization_0" -objects $obj

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_bus_skew_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_bus_skew_0" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'caribou_top_xlconcat_1_0_impl_1' run (if not found)
if {[string equal [get_runs -quiet caribou_top_xlconcat_1_0_impl_1] ""]} {
    create_run -name caribou_top_xlconcat_1_0_impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset caribou_top_xlconcat_1_0 -parent_run caribou_top_xlconcat_1_0_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs caribou_top_xlconcat_1_0_impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs caribou_top_xlconcat_1_0_impl_1]
}
set obj [get_runs caribou_top_xlconcat_1_0_impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'caribou_top_xlconcat_1_0_impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_init_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_opt_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_opt_report_drc_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_opt_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_io_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_io_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_utilization_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_control_sets_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_incremental_reuse_1" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_place_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_post_place_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_drc_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_methodology_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_methodology_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_power_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_power_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_route_status_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_route_status_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_timing_summary_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_incremental_reuse_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_route_report_clock_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_route_report_clock_utilization_0" -objects $obj

}
# Create 'caribou_top_xlconcat_1_0_impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name caribou_top_xlconcat_1_0_impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs caribou_top_xlconcat_1_0_impl_1
}
set obj [get_report_configs -of_objects [get_runs caribou_top_xlconcat_1_0_impl_1] caribou_top_xlconcat_1_0_impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "caribou_top_xlconcat_1_0_impl_1_post_route_phys_opt_report_timing_summary_0" -objects $obj

}
set obj [get_runs caribou_top_xlconcat_1_0_impl_1]
set_property -name "constrset" -value "caribou_top_xlconcat_1_0" -objects $obj
set_property -name "include_in_archive" -value "0" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'impl_2' run (if not found)
if {[string equal [get_runs -quiet impl_2] ""]} {
    create_run -name impl_2 -part xc7z045ffg900-2 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_2
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_2]
  set_property flow "Vivado Implementation 2018" [get_runs impl_2]
}
set obj [get_runs impl_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_2_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_init_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_opt_report_drc_0" -objects $obj

}
# Create 'impl_2_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0] "" ] } {
  create_report_config -report_name impl_2_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_place_report_io_0" -objects $obj

}
# Create 'impl_2_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_2_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_place_report_utilization_0" -objects $obj

}
# Create 'impl_2_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_2_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_place_report_control_sets_0" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_place_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_place_report_incremental_reuse_1" -objects $obj

}
# Create 'impl_2_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_place_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_post_place_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_2_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_drc_0" -objects $obj

}
# Create 'impl_2_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_2_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_methodology_0" -objects $obj

}
# Create 'impl_2_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0] "" ] } {
  create_report_config -report_name impl_2_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_power_0" -objects $obj

}
# Create 'impl_2_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_2_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_route_status_0" -objects $obj

}
# Create 'impl_2_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_2_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_2_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_clock_utilization_0" -objects $obj

}
# Create 'impl_2_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_route_report_bus_skew_0" -objects $obj

}
# Create 'impl_2_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_post_route_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_2_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_2_post_route_phys_opt_report_bus_skew_0" -objects $obj

}
set obj [get_runs impl_2]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_2]

puts "INFO: Project created:${_xil_proj_name_}"
set obj [get_dashboards default_dashboard]

# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ]
set_property -name "reports" -value "impl_2#impl_2_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_2#impl_2_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ]
set_property -name "reports" -value "impl_2#impl_2_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ]
set_property -name "reports" -value "impl_2#impl_2_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_2#synth_2_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_2#impl_2_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
# Set current dashboard to 'default_dashboard' 
current_dashboard default_dashboard 
