# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci
# IP: The module: 'PLL_40MHz_to_640MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xci
# IP: The module: 'PLL_40MHz_to_640MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/ip/PLL_40MHz_to_640MHz/PLL_40MHz_to_640MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_40MHz_to_640MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
