# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1.xci
# IP: The module: 'caribou_top_axi_iic_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'caribou_top_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'caribou_top_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1.xci
# IP: The module: 'caribou_top_axi_iic_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'caribou_top_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pct/Caribou/MPW4_Helmut/MPW4/caribou-soc/caribou-soc.srcs/sources_1/bd/caribou_top/ip/caribou_top_axi_iic_0_1/caribou_top_axi_iic_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'caribou_top_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
